# frozen_string_literal: true

require 'yaml'

module Senren
  module Rails
    # Generates a single source-of-truth rules file plus adapter files for
    # Copilot, Cursor, Claude, and Codex.
    #
    # Adapter files are marker-managed to avoid overwriting existing project
    # instructions outside Senren's generated block.
    class AgentRulesWriter
      START_MARKER = '<!-- senren:agent:start -->'
      END_MARKER   = '<!-- senren:agent:end -->'

      attr_reader :registry, :paths

      def initialize(registry: Registry.load!, paths: HostPaths.new)
        @registry = registry
        @paths    = paths
      end

      def sync!
        paths.ensure_agent_dirs!
        files = []
        files << write_full_file(paths.agent_rules_file, render_source_rules)
        files << write_adapter_file(paths.codex_agents_md, render_codex_adapter)
        files << write_adapter_file(paths.claude_md, render_claude_adapter)
        files << write_adapter_file(paths.copilot_instructions, render_copilot_adapter)
        files << write_adapter_file(paths.cursor_rule_file, render_cursor_adapter, prefix: cursor_frontmatter)
        files
      end

      private

      def installed_names
        path = paths.installed_components
        return [] unless path.exist?

        ledger = YAML.safe_load_file(path) || {}
        Array(ledger['installed']).filter_map { |entry| registry.find(entry['name']) }.map(&:name).sort
      end

      def render_source_rules
        names = installed_names
        <<~MD
          # Senren Agent Rules

          Generated by senren-ui. Do not edit by hand.
          Run `bin/rails senren:agents:sync` to regenerate.

          This file is the Senren source of truth for AI coding agents in this app.

          ## Hard Rules

          - Use Senren components before writing custom HTML.
          - Use ViewComponent for reusable UI.
          - Use Turbo for server state.
          - Use Stimulus only for local behavior.
          - Do not introduce React, Vue, Alpine, or external state frameworks.
          - Use semantic Tailwind tokens; do not hard-code color families.

          ## Important Files

          - `.senren/skill.md`                 - centralized component guidance
          - `.senren/conventions.md`           - project conventions
          - `.senren/registry.yml`             - component registry mirror
          - `.senren/installed_components.yml` - local install ledger

          ## Installed Components (#{names.size})

          #{format_names(names)}
        MD
      end

      def render_codex_adapter
        <<~MD
          ## Senren UI

          Follow `.senren/agent-rules.md` as the source of truth.

          - Prefer Senren components before custom HTML.
          - Keep reusable UI in ViewComponent.
          - Use Turbo for server state, Stimulus for local behavior.
          - Do not add React, Vue, Alpine, or external state frameworks.
          - Use semantic Tailwind tokens.
        MD
      end

      def render_claude_adapter
        <<~MD
          ## Senren UI

          @.senren/agent-rules.md

          Apply Senren conventions and component-first rules from the imported file.
        MD
      end

      def render_copilot_adapter
        <<~MD
          ## Senren UI

          Use `.senren/agent-rules.md` as the source of truth for this repository.

          - Prefer Senren components before custom HTML.
          - Reusable UI must use ViewComponent.
          - Turbo handles server state; Stimulus handles local behavior.
          - Do not introduce React, Vue, Alpine, or external state frameworks.
          - Use semantic Tailwind tokens.
        MD
      end

      def render_cursor_adapter
        <<~MD
          ## Senren UI

          Follow `.senren/agent-rules.md` as the source of truth.

          - Prefer Senren components before custom HTML.
          - Reusable UI uses ViewComponent.
          - Turbo for server state, Stimulus for local behavior.
          - No React/Vue/Alpine/external state frameworks.
          - Use semantic Tailwind tokens.
        MD
      end

      def cursor_frontmatter
        <<~MDC
          ---
          description: Senren UI repository conventions
          alwaysApply: true
          ---
        MDC
      end

      def format_names(names)
        return '_No components installed yet._' if names.empty?

        names.map { |name| "- #{name}" }.join("\n")
      end

      def write_full_file(path, content)
        atomic_write(path, content)
        path
      end

      def write_adapter_file(path, generated, prefix: '')
        existing = path.exist? ? path.read : prefix.to_s
        updated = inject(existing, generated)
        atomic_write(path, updated)
        path
      end

      def inject(existing, generated)
        if existing.include?(START_MARKER) && existing.include?(END_MARKER)
          before = existing.split(START_MARKER, 2).first
          tail = existing.split(START_MARKER, 2).last
          after = tail.split(END_MARKER, 2).last
          "#{before}#{START_MARKER}\n\n#{generated.rstrip}\n\n#{END_MARKER}#{after}"
        else
          body = existing.rstrip
          prefix = body.empty? ? '' : "#{body}\n\n"
          "#{prefix}#{START_MARKER}\n\n#{generated.rstrip}\n\n#{END_MARKER}\n"
        end
      end

      def atomic_write(path, content)
        tmp = "#{path}.tmp"
        File.write(tmp, content)
        File.rename(tmp, path)
      end
    end
  end
end
