# frozen_string_literal: true

require 'yaml'

module Senren
  module Rails
    # Generates public/llms.txt and public/llms-full.txt for AI discoverability.
    # The entire content of both files is owned by this writer; do not edit by hand.
    class LlmsWriter
      attr_reader :registry, :paths

      def initialize(registry: Registry.load!, paths: HostPaths.new)
        @registry = registry
        @paths    = paths
      end

      def generate!
        paths.llms_short.parent.mkpath
        paths.llms_full.parent.mkpath
        atomic_write(paths.llms_short, render_short)
        atomic_write(paths.llms_full,  render_full)
        [paths.llms_short, paths.llms_full]
      end

      private

      def installed
        path = paths.installed_components
        return [] unless path.exist?

        ledger = YAML.safe_load_file(path) || {}
        Array(ledger['installed']).filter_map { |e| registry.find(e['name']) }
      end

      def render_short
        names = installed.map(&:name).sort
        <<~TXT
          # Senren UI

          Generated by senren-ui. Do not edit by hand. Run
          `bin/rails senren:llms:generate` to regenerate.

          Senren UI is the local Rails UI system used by this application.
          Use `.senren/skill.md` as the primary AI Agent guide.

          ## Hard Rules

          - Use Senren components before writing custom HTML.
          - Use ViewComponent for reusable UI.
          - Use Turbo for server state.
          - Use Stimulus only for local behavior.
          - Do not introduce React, Vue, Alpine, or any external state framework.
          - Do not hard-code colors; use semantic Tailwind tokens.

          ## Important Files

          - `.senren/skill.md`              - centralized AI agent guide
          - `.senren/registry.yml`          - mirror of installable components
          - `.senren/installed_components.yml` - what is currently installed
          - `.senren/conventions.md`        - Senren conventions for humans and agents

          ## Installed Components (#{names.size})

          #{names.map { |n| "- #{n}" }.join("\n")}
        TXT
      end

      def render_full
        comps = installed.sort_by(&:name)

        out = []
        out << '# Senren UI - Full Snapshot'
        out << ''
        out << 'Generated by senren-ui. Do not edit by hand. Run'
        out << '`bin/rails senren:llms:generate` to regenerate.'
        out << ''
        out << '## Hard Rules'
        out << ''
        out << '- Use Senren components before writing custom HTML.'
        out << '- Server-rendered HTML first; ViewComponent for reusable UI.'
        out << '- Hotwire (Turbo + Stimulus) is the only client runtime.'
        out << '- TailwindCSS with semantic tokens (`bg-background`, `text-foreground`, ...).'
        out << '- Do not introduce React, Vue, Alpine, or external state frameworks.'
        out << '- Components copied into `app/components/senren/` are owned by this app; edit them directly.'
        out << ''
        out << '## Installed Component Inventory'
        out << ''

        registry.groups.each do |group|
          group_comps = comps.select { |c| c.category == group['id'] }
          next if group_comps.empty?

          out << "### #{group['title']}"
          out << ''
          out << group['description'].to_s
          out << ''
          group_comps.each { |c| out << render_component(c) }
        end

        out << '## Recipes'
        out << ''
        registry.recipes.each do |id, recipe|
          out << "### #{id}"
          out << ''
          out << recipe['description'].to_s
          out << ''
          out << 'Components:'
          recipe['components'].each { |c| out << "- #{c}" }
          out << ''
        end

        out.join("\n")
      end

      def render_component(comp)
        ruby_class = "Senren::#{comp.name.split('_').map { |w| w[0].upcase + w[1..] }.join}Component"
        s = []
        s << "#### #{comp.name}#{'  (stub)' if comp.stub?}"
        s << ''
        s << "Category: #{comp.category}.  " \
             "Client: #{comp.client? ? "yes (#{comp.controller})" : 'no'}.  " \
             "Variants: #{comp.variants.empty? ? 'none' : comp.variants.join(', ')}."
        s << ''
        s << "Use for: #{comp.use_for.join('; ')}." unless comp.use_for.empty?
        s << "Avoid: #{comp.avoid.join('; ')}." unless comp.avoid.empty?
        s << ''
        s << 'Rails usage:'
        s << ''
        s << '```erb'
        s << if comp.variants.any?
               "<%= render #{ruby_class}.new(variant: :#{comp.variants.first}) do %>"
             else
               "<%= render #{ruby_class}.new do %>"
             end
        s << '  ...'
        s << '<% end %>'
        s << '```'
        s << ''
        s.join("\n")
      end

      def atomic_write(path, content)
        tmp = "#{path}.tmp"
        File.write(tmp, content)
        File.rename(tmp, path)
      end
    end
  end
end
