# frozen_string_literal: true

require 'yaml'

module Senren
  module Rails
    # Writes the centralized .senren/skill.md file for AI agents.
    #
    # The file contains a generated region delimited by HTML comments:
    #
    #   <!-- senren:skill:start -->
    #   ...generated by SkillWriter...
    #   <!-- senren:skill:end -->
    #
    # Anything outside that region is preserved across regeneration.
    class SkillWriter
      START_MARKER = '<!-- senren:skill:start -->'
      END_MARKER   = '<!-- senren:skill:end -->'

      GROUP_ORDER = %w[actions forms overlays navigation layout data saas rich].freeze

      attr_reader :registry, :paths

      def initialize(registry: Registry.load!, paths: HostPaths.new)
        @registry = registry
        @paths    = paths
      end

      def sync!
        installed = installed_names
        body = render(installed)

        paths.senren_dir.mkpath
        existing = paths.skill_file.exist? ? paths.skill_file.read : default_outer_template

        new_content = inject(existing, body)
        paths.skill_file.write(new_content)
        paths.skill_file
      end

      private

      def installed_names
        path = paths.installed_components
        return [] unless path.exist?

        ledger = YAML.safe_load_file(path) || {}
        Array(ledger['installed']).filter_map { |e| e['name'] }.uniq
      end

      def render(installed_names)
        if installed_names.empty?
          return '_No Senren components installed yet. Run `bin/rails senren:add <name>...` to install components._'
        end

        lines = []
        installed = installed_names.filter_map { |n| registry.find(n) }

        registry.groups.each do |group|
          gid = group['id']
          comps = installed.select { |c| c.category == gid }
          next if comps.empty?

          lines << "## #{group['title']}"
          lines << ''
          lines << group['description'].to_s
          lines << ''
          comps.sort_by(&:name).each { |c| lines << render_component(c) }
        end

        lines.join("\n")
      end

      def render_component(comp)
        out = []
        out << "### Component: #{humanize(comp.name)}"
        out << ''
        out << "- **Category**: #{comp.category}"
        out << "- **Stub**: #{comp.stub? ? 'yes (placeholder)' : 'no'}"
        out << "- **Client behavior**: #{client_summary(comp)}"
        out << "- **Depends on**: #{format_list(comp.depends_on)}"
        out << "- **Pairs with**: #{format_list(comp.pairs_with)}"
        out << "- **Variants**: #{format_list(comp.variants)}"
        out << ''
        out << '**Use for**:'
        comp.use_for.each { |u| out << "- #{u}" }
        out << ''
        out << '**Avoid**:'
        comp.avoid.each { |a| out << "- #{a}" }
        out << ''
        out << '**Accessibility**:'
        comp.accessibility.each { |a| out << "- #{a}" }
        out << ''
        out << '**Rails usage**:'
        out << ''
        out << '```erb'
        out << render_usage_example(comp)
        out << '```'
        out << ''
        "#{out.join("\n")}\n"
      end

      def render_usage_example(comp)
        ruby_class = "Senren::#{ruby_class_for(comp.name)}Component"
        if comp.variants.any?
          variant = comp.variants.first
          %(<%= render #{ruby_class}.new(variant: :#{variant}) do %>\n  ...\n<% end %>)
        else
          %(<%= render #{ruby_class}.new do %>\n  ...\n<% end %>)
        end
      end

      def client_summary(comp)
        return 'none' unless comp.client?

        path = "app/javascript/controllers/senren/#{comp.name}_controller.js"
        "Stimulus `#{comp.controller}` (`#{path}`)"
      end

      def format_list(items)
        return '_none_' if items.empty?

        items.map { |i| "`#{i}`" }.join(', ')
      end

      def humanize(name)
        name.split('_').map { |w| w[0].upcase + w[1..] }.join
      end

      def ruby_class_for(name)
        humanize(name)
      end

      def inject(existing, generated_body)
        if existing.include?(START_MARKER) && existing.include?(END_MARKER)
          before = existing.split(START_MARKER, 2).first
          after  = existing.split(END_MARKER, 2).last
          "#{before}#{START_MARKER}\n\n#{generated_body}\n\n#{END_MARKER}#{after}"
        else
          "#{existing.rstrip}\n\n#{START_MARKER}\n\n#{generated_body}\n\n#{END_MARKER}\n"
        end
      end

      def default_outer_template
        <<~MD
          # Senren Skill File

          This file is the central guide for AI coding agents working in this app.

          ## Hard Rules

          - Use Senren components before writing custom HTML.
          - Use ViewComponent for reusable UI; Turbo for server state; Stimulus for local behavior only.
          - Do not introduce React, Vue, Alpine, or any external state framework.
          - Do not hard-code colors; use semantic Tailwind tokens like `bg-background`, `text-foreground`, `bg-primary`.

          ## Installed Components

          The block between the markers below is generated by `bin/rails senren:skill:sync`.
          Do not edit the generated region by hand. You may add notes outside the markers.

        MD
      end
    end
  end
end
