# frozen_string_literal: true

require 'yaml'
require 'senren/rails/marker_block'
require 'senren/rails/safe_write'

module Senren
  module Rails
    # Writes the centralized .senren/skill.md file for AI agents.
    #
    # The file contains a generated region delimited by HTML comments:
    #
    #   <!-- senren:skill:start -->
    #   ...generated by SkillWriter...
    #   <!-- senren:skill:end -->
    #
    # Anything outside that region is preserved across regeneration.
    class SkillWriter
      START_MARKER = '<!-- senren:skill:start -->'
      END_MARKER   = '<!-- senren:skill:end -->'

      GROUP_ORDER = %w[actions forms overlays navigation layout data saas rich].freeze

      attr_reader :registry, :paths

      def initialize(registry: Registry.load!, paths: HostPaths.new)
        @registry = registry
        @paths    = paths
      end

      def sync!
        installed = installed_names
        body = render(installed)

        SafeWrite.mkdir_p!(paths.senren_dir, paths.root, 'skill.md')
        existing = paths.skill_file.exist? ? paths.skill_file.read : default_outer_template

        new_content = inject(existing, body)
        atomic_write(paths.skill_file, new_content)
        paths.skill_file
      end

      private

      # Matches AgentRulesWriter: a killed process must not truncate the file,
      # and a symlinked .senren must not redirect the write outside the app.
      def atomic_write(path, content)
        SafeWrite.assert_inside!(path, paths.root, path.to_s)
        tmp = path.parent.join("#{path.basename}.#{Process.pid}.tmp")
        File.write(tmp, content)
        File.rename(tmp, path)
      end

      def installed_names
        path = paths.installed_components
        return [] unless path.exist?

        ledger = YAML.safe_load_file(path) || {}
        Array(ledger['installed']).filter_map { |e| e['name'] }.uniq
      end

      def render(installed_names)
        if installed_names.empty?
          return '_No Senren components installed yet. Run `bin/rails senren:add button` to install components._'
        end

        lines = []
        installed = installed_names.filter_map { |n| registry.find(n) }

        registry.groups.each do |group|
          gid = group['id']
          comps = installed.select { |c| c.category == gid }
          next if comps.empty?

          lines << "## #{group['title']}"
          lines << ''
          lines << group['description'].to_s
          lines << ''
          comps.sort_by(&:name).each { |c| lines << render_component(c) }
        end

        lines.join("\n")
      end

      def render_component(comp)
        out = []
        out << "### Component: #{humanize(comp.name)}"
        out << ''
        out << "- **Category**: #{comp.category}"
        out << "- **Stub**: #{comp.stub? ? 'yes (placeholder)' : 'no'}"
        out << "- **Client behavior**: #{client_summary(comp)}"
        out << "- **Depends on**: #{format_list(comp.depends_on)}"
        out << "- **Pairs with**: #{format_list(comp.pairs_with)}"
        out << "- **Variants**: #{format_list(comp.variants)}"
        out << ''
        out << '**Use for**:'
        comp.use_for.each { |u| out << "- #{u}" }
        out << ''
        out << '**Avoid**:'
        comp.avoid.each { |a| out << "- #{a}" }
        out << ''
        out << '**Accessibility**:'
        comp.accessibility.each { |a| out << "- #{a}" }
        out << ''
        out << '**Rails usage**:'
        out << ''
        out << '```erb'
        out << render_usage_example(comp)
        out << '```'
        out << ''
        "#{out.join("\n")}\n"
      end

      def render_usage_example(comp)
        ruby_class = "Senren::#{ruby_class_for(comp.name)}Component"
        if comp.variants.any?
          variant = comp.variants.first
          %(<%= render #{ruby_class}.new(variant: :#{variant}) do %>\n  ...\n<% end %>)
        else
          %(<%= render #{ruby_class}.new do %>\n  ...\n<% end %>)
        end
      end

      # Describes what is installed, not what the registry offers.
      #
      # This rendered the registry default, so after `senren:add select
      # --no-client` the skill file told agents to use
      # `senren--select` and named a controller file that is not on disk. The
      # copier computes the truth and writes it to the ledger — with a comment
      # saying "never record client behavior in the ledger that was not
      # installed" — and nothing read it back. The gem's flagship feature was
      # wrong for precisely the installs where the flag was exercised.
      def client_summary(comp)
        return 'none' unless comp.client?
        return 'none (installed without its Stimulus controller)' unless installed_with_client?(comp.name)

        path = "app/javascript/controllers/senren/#{comp.name}_controller.js"
        "Stimulus `#{comp.controller}` (`#{path}`)"
      end

      # nil when the ledger predates this field, in which case the registry
      # default is the best available answer.
      def installed_with_client?(name)
        entry = ledger_entries.find { |e| e['name'] == name }
        return true if entry.nil? || !entry.key?('client')

        entry['client']
      end

      def ledger_entries
        @ledger_entries ||= begin
          path = paths.installed_components
          path.exist? ? Array((YAML.safe_load_file(path) || {})['installed']) : []
        end
      end

      def format_list(items)
        return '_none_' if items.empty?

        items.map { |i| "`#{i}`" }.join(', ')
      end

      # NAME_PATTERN accepts consecutive underscores, and "foo__bar".split("_")
      # yields an empty segment, so w[0] was nil and this raised NoMethodError —
      # after the files were copied and the ledger written, leaving a
      # half-completed install. Empty segments are dropped instead.
      def humanize(name)
        name.split('_').reject(&:empty?).map { |w| w[0].upcase + w[1..] }.join
      end

      def ruby_class_for(name)
        humanize(name)
      end

      def inject(existing, generated_body)
        MarkerBlock.inject(
          existing, generated_body,
          start_marker: START_MARKER, end_marker: END_MARKER, label: paths.skill_file.to_s
        )
      end

      def default_outer_template
        <<~MD
          # Senren Skill File

          This file is the central guide for AI coding agents working in this app.

          ## Hard Rules

          - Use Senren components before writing custom HTML.
          - Use ViewComponent for reusable UI; Turbo for server state; Stimulus for local behavior only.
          - Do not introduce React, Vue, Alpine, or any external state framework.
          - Do not hard-code colors; use semantic Tailwind tokens like `bg-background`, `text-foreground`, `bg-primary`.

          ## Installed Components

          The block between the markers below is generated by `bin/rails senren:skill:sync`.
          Do not edit the generated region by hand. You may add notes outside the markers.

        MD
      end
    end
  end
end
