# frozen_string_literal: true

require 'json'

# The catalogue of every string a component shows or announces, read straight
# out of the component source.
#
# The English lives in the code, as the `default:` of a `senren_t` call, and
# nowhere else is allowed to be the source of truth for it: a copy kept by hand
# in a locale file drifts the first time someone edits a label. So
# `templates/locales/senren.en.yml` is *generated* from these calls
# (`bin/i18n-sync`) and a test fails if the two ever disagree.
#
# Development tooling, so it lives in scripts/ rather than lib/: the gemspec
# ships only lib, registry, templates and docs, and nothing here reaches a host
# app.
#
# Only a literal call is understood:
#
#   senren_t('pagination.next', default: 'Next')
#   senren_t('cart.remove_item', default: 'Remove %{name}', name: item[:name])
#
# A key or a default built at runtime cannot be read without running the
# component, and a string the catalogue cannot see is a string nobody can
# translate. Such a call is reported as a problem, not skipped.
class I18nCatalog
  Entry = Struct.new(:key, :default, :file, :line, keyword_init: true)

  # A Ruby string literal with no interpolation. Single quotes allow `\'` and
  # `\\`; double quotes allow no backslash at all, because the unescaping below
  # handles only what it was written for.
  STRING = /'(?:[^'\\]|\\['\\])*'|"(?:[^"\\#]|#(?!\{))*"/
  CALL_AT = /\Gsenren_t\(\s*(?<key>#{STRING})\s*,\s*default:\s*(?<default>#{STRING})/m
  VARIABLE = /%\{(\w+)\}/
  KEY_PATTERN = /\A[a-z][a-z0-9_]*(\.[a-z][a-z0-9_]*)+\z/

  SHARED = 'shared'
  HEADER = <<~TEXT
    # Senren UI - English strings. This is the canonical wording.
    #
    # GENERATED by bin/i18n-sync from the senren_t(key, default:) calls in
    # templates/components. Do not edit it by hand: change the `default:` in the
    # component and run bin/i18n-sync, or a test will fail.
    #
    # Copy this file to senren.<locale>.yml, change the top-level `en:` to your
    # locale, and translate the values. Keep every %{variable} - they are filled in
    # when the component renders. A key you leave out falls back to the English.
  TEXT

  attr_reader :root

  def initialize(root:)
    @root = File.expand_path(root)
  end

  # Component source in the order a translator would read it: components
  # alphabetically, and within one the Ruby first, because that is where the
  # constructor defaults (the labels and placeholders) are, then the template.
  def source_files
    Dir[File.join(root, 'templates/components/*/*')]
      .select { |path| path.end_with?('_component.rb', '.html.erb') }
      .sort_by { |path| [File.dirname(path), path.end_with?('.rb') ? 0 : 1, path] }
  end

  def entries
    scan.first
  end

  # Calls the catalogue cannot read, as `path:line: reason`.
  def problems
    scan.last
  end

  # Every key with its English default. A key used in two places must have the
  # same default in both, or one of them is wrong; see #conflicts.
  def defaults
    entries.each_with_object({}) { |entry, table| table[entry.key] ||= entry.default }
  end

  def conflicts
    entries.group_by(&:key).filter_map do |key, group|
      distinct = group.map(&:default).uniq
      next if distinct.size == 1

      "#{key} has #{distinct.size} defaults: #{distinct.map(&:inspect).join(' vs ')}"
    end
  end

  # A component may use its own namespace and `shared`, nothing else. Reaching
  # into another component's keys would make a change to one a surprise in the
  # other.
  def namespace_violations
    entries.filter_map do |entry|
      component = component_of(entry.file)
      namespace = entry.key.split('.').first
      next if [component, SHARED].include?(namespace)

      "#{entry.file}:#{entry.line}: #{entry.key} is outside senren.#{component}.*"
    end
  end

  def malformed_keys
    defaults.keys.grep_v(KEY_PATTERN)
  end

  # { 'shared' => ['accordion', ...] }: who uses each shared key.
  def users_of(key)
    entries.select { |entry| entry.key == key }.map { |entry| component_of(entry.file) }.uniq
  end

  # key => default, nested the way the YAML is: shared first, then components in
  # source order, and keys within a component in the order they are first used.
  def tree
    ordered = defaults.keys.each_with_index.sort_by do |key, index|
      [key.start_with?("#{SHARED}.") ? 0 : 1, namespace_rank(key), index]
    end

    ordered.each_with_object({}) { |(key, _), nested| insert(nested, key.split('.'), defaults.fetch(key)) }
  end

  def to_yaml(locale = 'en')
    lines = HEADER.lines.map(&:rstrip)
    lines << "#{locale}:"
    lines << '  senren:'
    emit(tree, 4, lines)
    "#{lines.join("\n")}\n"
  end

  def self.variables(text)
    text.to_s.scan(VARIABLE).flatten.sort.uniq
  end

  # Leaf keys of a nested hash as dotted paths, in document order.
  def self.flatten(hash, prefix = nil)
    hash.flat_map do |key, value|
      path = [prefix, key].compact.join('.')
      value.is_a?(Hash) ? flatten(value, path) : [[path, value]]
    end
  end

  private

  def scan
    @scan ||= begin
      entries = []
      problems = []
      source_files.each { |path| scan_file(path, entries, problems) }
      [entries, problems]
    end
  end

  def scan_file(path, entries, problems)
    source = blank_comments(File.read(path))
    relative = path.delete_prefix("#{root}/")
    position = 0

    while (index = source.index('senren_t(', position))
      line = source[0...index].count("\n") + 1
      match = CALL_AT.match(source, index)

      if match
        entries << Entry.new(key: literal(match[:key]), default: literal(match[:default]), file: relative, line: line)
      else
        problems << "#{relative}:#{line}: senren_t needs a literal key and a literal default:"
      end
      position = index + 1
    end
  end

  # Whole-line Ruby comments and ERB comments can mention `senren_t(` in prose.
  # They are blanked rather than removed so line numbers stay true.
  def blank_comments(source)
    source
      .gsub(/^[ \t]*#.*$/) { |comment| comment.gsub(/[^\n]/, ' ') }
      .gsub(/<%#.*?%>/m) { |comment| comment.gsub(/[^\n]/, ' ') }
  end

  def literal(token)
    body = token[1..-2]
    token.start_with?("'") ? body.gsub(/\\(['\\])/, '\1') : body
  end

  def component_of(file)
    file[%r{templates/components/([^/]+)/}, 1]
  end

  def namespace_rank(key)
    @namespace_order ||= defaults.keys.map { |name| name.split('.').first }.uniq
    @namespace_order.index(key.split('.').first)
  end

  def insert(nested, path, value)
    head, *rest = path
    if rest.empty?
      raise ArgumentError, "#{path.inspect} is both a key and a namespace" if nested[head].is_a?(Hash)

      nested[head] = value
    else
      nested[head] ||= {}
      raise ArgumentError, "#{head} is both a key and a namespace" unless nested[head].is_a?(Hash)

      insert(nested[head], rest, value)
    end
  end

  # Every value is double quoted. Unquoted, YAML 1.1 reads `Yes`, `No`, `On` and
  # `Off` as booleans, and a value starting with `%` is a directive. JSON string
  # syntax is valid YAML, so one escaper covers the quotes, backslashes and
  # control characters, and leaves Vietnamese and every other script as written.
  def emit(hash, indent, lines)
    hash.each do |key, value|
      if value.is_a?(Hash)
        lines << "#{' ' * indent}#{key}:"
        emit(value, indent + 2, lines)
      else
        lines << "#{' ' * indent}#{key}: #{JSON.generate(value)}"
      end
    end
  end
end
